### ISSUE TITLE
SyntaxError: https://jslib.k6.io/k8s-distributed-execution/0.0.1/index.js

### ISSUE THREAD

**Issue by erolg** [k6io/operator#10]
```
(ERRO[0003] SyntaxError: https://jslib.k6.io/k8s-distributed-execution/0.0.1/index.js: Unexpected token (2:4)
  1 |
> 2 |     <!DOCTYPE html>
    |     ^
  3 |     <html lang="en">
  4 |     <head>
  5 |       <meta charset="UTF-8"> at <eval>:2:28542(114))
```

**Comment by dgzlopes** [comment]
Hey @erolg! Thanks for creating the issue.

Probably this is related: https://github.com/k6io/jslib.k6.io/commit/6d51cc19acb795c6e81423c58342f34163da503a

@simskij thoughts on this?

**Comment by simskij** [comment]
Yeah! That lib is not needed anymore. Did I forget to update one of the examples? Will have a look tomorrow! 👍🏼💪🏼

**Comment by simskij** [comment]
Updated the readme. Just skip the part about execution segments. The operator will take care of it for you. Sorry for the inconvenience, @erolg!
