### ISSUE TITLE
Add k6 extensions support

### ISSUE THREAD

**Issue by majnos** [k6io/operator#18]
It would be very nice to have ability to run extensions on this distributed k6 deployment

**Comment by jmdacruz** [comment]
#17 would be one way of doing this. I was able to run the Prometheus extension (https://github.com/szkiba/xk6-prometheus) using these changes (building a custom image from `loadimpact/k6:latest` that replaces the `k6` binary with one built with the extension)

**Comment by dgzlopes** [comment]
Now that #17 has been merged, we can close this :)

btw, thanks for raising the issue!

**Comment by dgzlopes** [comment]
Now that #17 has been merged, we can close this :)

btw, thanks for raising the issue!
