### ISSUE TITLE
The operator specifically requires kustomize version 3.8.1 to work

### ISSUE THREAD

**Issue by simskij** [k6io/operator#29]
> Ok I reverted to 3.8.1 and it seemed to not throw the kitchen sink at me.
>
> For anyone else, you can use this to install a specific version of kustomize:
> `https://github.com/kubernetes-sigs/kustomize/blob/master/hack/install_kustomize.sh`
> 
> Then run:
> `./install_kustomize.sh [WANTED_VERSION]`
>
> The downloaded bin file should be moved to the appropriate place.
>
> In all honesty though, this should probably be fixed somehow.

_Originally posted by @basickarl in https://github.com/k6io/operator/issues/19#issuecomment-852879662_

**Comment by KnechtionsCoding** [comment]
I don't think this is true:

I was able to build and output using:

```bash
kustomize version                                                                                                  [8:00:55]
{Version:kustomize/v4.0.5 GitCommit:9e8e7a7fe99ec9fbf801463e8607928322fc5245 BuildDate:2021-03-08T22:52:48+00:00 GoOs:darwin GoArch:amd64}
```

I know 3.8.1/3.8.x in general has some issues. We've had similar issues with a particular version of ArgoCD that bundled the 3.8.1 version in it and rendering kustomize improperly.

**Comment by simskij** [comment]
Ah, great! I went ahead and created the issue without verifying the issue just to make sure it wouldn't get lost in transmission. If that's the case, we can go ahead and close this again 👍🏽
