### ISSUE TITLE
Allow the K6 CRD to set environment variables for the runners.

### ISSUE THREAD

**Issue by simskij** [k6io/operator#32]
> I did not get `-e` argument working.
> 
> I got following errors:
> ```
> time="2021-06-04T14:51:39Z" level=error msg="Couldn't flush a batch" error="write udp 127.0.0.1:36848->127.0.0.1:8125: write: connection refused" output=statsd
> ```
> 
> While having following manifest:
> ```
> apiVersion: k6.io/v1alpha1
> kind: K6
> metadata:
>   name: k6-sample
> spec:
>   parallelism: 4
>   script: crocodile-stress-test
>   arguments: -e K6_STATSD_ADDR=graphite-1622816495:8125 --out statsd
>   ```
>   
> This popped up job with commands:
> ```
> k6 run --quiet --execution-segment=0:1/4 --execution-segment- sequence=0,1/4,2/4,3/4,1 -e K6_STATSD_ADDR=graphite-1622816495:8125 --out statsd /test/test.js --address=0.0.0.0:6565 --paused
> 
> /\ |‾‾| /‾‾/ /‾‾/
> /\ / \ | |/ / / /
> / \/ \ | ( / ‾‾\
> / \ | |\ \ | (‾) |
> / __________ \ |__| \__\ \_____/ .io
> execution: local
> script: /test/test.js
> output: statsd (localhost:8125)
> ```
> 
> But this doesn't work locally either. Unless I run the command as follow:
> ```
> $ K6_STATSD_ADDR=graphite-1622816495:8125 k6 run --quiet --execution-segment=0:1/4 --execution-segment-sequence=0,1/4,2/4,3/4,1 -e K6_STATSD_ADDR=graphite-1622816495:8125 --out statsd ./test.js --address=0.0.0.0:6565 --paused
> 
>           /\      |‾‾| /‾‾/   /‾‾/   
>      /\  /  \     |  |/  /   /  /    
>     /  \/    \    |     (   /   ‾‾\  
>    /          \   |  |\  \ |  (‾)  | 
>   / __________ \  |__| \__\ \_____/ .io
> 
> ERRO[0000] The moduleSpecifier "./test.js" couldn't be found on local disk. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://k6.io/docs/using-k6/modules#using-local-modules-with-docker.
> ```

_Originally posted by @mikaelkundert in https://github.com/k6io/operator/issues/15#issuecomment-863844617_

Using -e won't work, just as @mikaelkundert points out. What that does is that it allows the k6 script to use it as an environment variable. However, the statsd output is initiated outside of the actual test script. Instead, we should add support for providing env vars through the CRD.

**Comment by mikaelkundert** [comment]
I noticed that error message was about missing `test.js`, but here's the actual error message that indicates that latter command should work.

```
$ K6_STATSD_ADDR=graphite-1622816495:8125 k6 run --quiet --execution-segment=0:1/4 --execution-segment-sequence=0,1/4,2/4,3/4,1 -e K6_STATSD_ADDR=graphite-1622816495:8125 --out statsd ./test.js --address=0.0.0.0:6565 --paused

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

ERRO[0000] Couldn't make buffered client, lookup graphite-1622816495 on 127.0.0.53:53: server misbehaving  output=statsd
ERRO[0000] lookup graphite-1622816495 on 127.0.0.53:53: server misbehaving 
```

**Comment by mikaelkundert** [comment]
Command seems to be assembled by `jobs.NewRunnerJob` at https://github.com/k6io/operator/blob/main/pkg/resources/jobs/runner.go#L24L115.

My initial vision for how to specify those environment variables would be using familiar `env` pattern such as:
```
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script: crocodile-stress-test
  env:
    - name: K6_STATSD_ADDR
      value: graphite-1622816495:8125
  arguments: --out statsd
```

**Comment by simskij** [comment]
Yes, that would be my suggestion as well!
